
name: 'jaffle_shop'
version: '0.1'
profile: 'default'
config-version: 2

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

models:
  +database: ANALYTICS
  jaffle_shop:
      materialized: table
      staging:
        materialized: view


seeds:
  +database: raw
  +schema: jaffle_shop